//! `git dupe status`, `add .`, `commit -m x`, `switch`, `log -1`, and `clean -n` in a
//! generated public repository of 100,000 tracked files with hidden paths in three
//! directories, once with 200 privately tracked files and once with 2,000: each runs Git
//! the fixed sequence `Holds/G22` names for it, so the same number of times at both sizes,
//! and finishes within one second on a warm cache; public `git status` takes the same time
//! as before attachment within measurement noise (`Done when`, G22).
//!
//! How it is measured:
//! - The runs counted are those git-dupe itself starts (`Runs::own`), not the Git process
//!   that dispatches `dupe` or what a Git command starts in turn, and their command words
//!   are compared with the sequence written below, the same under every release.
//! - Warm cache: every timed command runs after an untimed public `git status` and an
//!   untimed `git dupe status --porcelain -z` have read the workspace since its files were
//!   last written. The second also shows `status` confined at this size: it lists every
//!   changed private file and nothing of the public ones (G12).
//! - The time of a command at a size is the least of three rounds, each round changing
//!   every private file first, so that `add .` and `commit -m x` have work: other load on
//!   the machine only adds time, so the least is the estimate. It is the wall time of the
//!   whole `git dupe …` run, its trace written and read back included, and it must be
//!   under one second, the product's number.
//! - Within measurement noise: public `git status` is timed eleven times before
//!   `git dupe init` and eleven times after the last round, and the least after is not
//!   above the greatest before. The number is fixed here, never raised because a
//!   comparison failed, and no factor is applied.
//! - The build is the one `cargo test` makes, unoptimized.
//! - The repository is generated by the release under test in the scenario's own
//!   directory: a hundred directories of a thousand empty files. The three hidden
//!   directories lie inside three of them, so that the walk G22 bounds has large
//!   neighbours to stay out of.

use std::fs::{self, File, OpenOptions};
use std::io::Write;
use std::path::Path;
use std::time::{Duration, Instant, SystemTime};

use crate::harness::{End, Scenario, region_rules, report, run_traced, under_each_release};

const DIRECTORIES: usize = 100;
const FILES_PER_DIRECTORY: usize = 1_000;
const PUBLIC_FILES: usize = DIRECTORIES * FILES_PER_DIRECTORY;
/// The hidden directories, each inside a public directory of a thousand files.
const HIDDEN: [&str; 3] = ["d00/notes", "d50/notes", "d99/notes"];
/// The privately tracked files, `.gitdupe` among them.
const SIZES: [usize; 2] = [200, 2_000];
const ROUNDS: usize = 3;
const PUBLIC_TIMINGS: usize = 11;
const BOUND: Duration = Duration::from_secs(1);
/// The private branch `switch` moves to, whose tree differs in every private file.
const OTHER: &str = "other";
const COMMANDS: [&[&str]; 6] = [
    &["status"],
    &["add", "."],
    &["commit", "-m", "x"],
    &["log", "-1"],
    &["clean", "-n"],
    &["switch", OTHER],
];

/// The Git runs `Holds/G22` names for `git dupe <command> …` in this workspace, in order:
/// `.gitdupe` stands on disk, so the hidden paths need no `cat-file`, no word is an
/// alias, and no directory above a hidden path holds a `.git` entry.
fn sequence(command: &'static str) -> Vec<&'static str> {
    // The runner's locate.
    let mut runs = vec!["rev-parse"];
    match command {
        // The hidden paths' private listing, the staged deletions (`Holds/G12`), the public
        // listing under the scope, and the confined `status`.
        "status" => runs.extend(["ls-files", "diff", "ls-files", "status"]),
        // The hidden paths' private listing, the public listing under the scope and
        // `.gitdupe`, the question which of the form's paths an ignore rule matches
        // (`Holds/G13, G14`: none here, so no second `add`), and the `add`.
        "add" => runs.extend(["ls-files", "ls-files", "check-ignore", "add"]),
        // The hidden paths' private listing and the `clean`; without `-X`, no ignore
        // question, and with no `.git` entry above a hidden path, no public listing
        // (`Holds/G16`).
        "clean" => runs.extend(["ls-files", "clean"]),
        // The alias lookup of a word git-dupe neither adds, changes, nor guards
        // (`Holds/G19`), then the command itself.
        word => runs.extend(["config", word]),
    }
    // Settle: the hidden paths' private listing, the public listing under the region
    // paths, and the exposure question.
    runs.extend(["ls-files", "ls-files", "check-ignore"]);
    runs
}

/// What one timed command did in one round.
struct Measured {
    /// The command words of the Git runs git-dupe itself started.
    runs: Vec<Vec<u8>>,
    took: Duration,
}

#[test]
fn six_commands_run_git_a_fixed_number_of_times_within_a_second_among_100000_files() {
    under_each_release(|s| {
        let version = s.git(["--version"]).succeeds().stdout;
        let version = String::from_utf8_lossy(version.trim_ascii_end()).into_owned();
        let version = version.trim_start_matches("git version ");
        let dir = s.dir().join("project");
        s.git(["config", "--global", "maintenance.auto", "false"])
            .succeeds();
        generate(s, &dir);
        let before = public_status_timings(s, &dir);
        s.init(&dir);

        // `measured[command][size]` holds one entry per round.
        let mut measured: Vec<Vec<Vec<Measured>>> = COMMANDS
            .iter()
            .map(|_| SIZES.iter().map(|_| Vec::new()).collect())
            .collect();
        let mut written = 0;
        for (at, size) in SIZES.into_iter().enumerate() {
            // `.gitdupe` is the one privately tracked file outside the hidden directories.
            let files = size - 1;
            write_private_files(&dir, written..files);
            written = files;
            s.git(["dupe", "add"].into_iter().chain(HIDDEN))
                .from(&dir)
                .succeeds();
            s.git(["dupe", "commit", "-q", "-m", "private files"])
                .from(&dir)
                .succeeds();
            s.git(["dupe", "branch", "-f", OTHER]).from(&dir).succeeds();
            let tracked = s.private(&dir).git(["ls-files", "-z"]).succeeds();
            let tracked = tracked.stdout.iter().filter(|&&byte| byte == 0).count();
            assert_eq!(tracked, size, "privately tracked files");
            let rules: Vec<Vec<u8>> = [".gitdupe"]
                .into_iter()
                .chain(HIDDEN)
                .map(|path| format!("/{path}").into_bytes())
                .collect();
            assert_eq!(region_rules(&dir), rules, "the hidden paths");

            for round in 0..ROUNDS {
                let line = format!("round {round} at {size}");
                change_private_files(&dir, files, &line);
                s.git(["status"]).from(&dir).succeeds();
                status_lists_the_changed_private_files_alone(s, &dir, files);
                for (command, words) in COMMANDS.into_iter().enumerate() {
                    let started = Instant::now();
                    let (output, runs) = run_traced(
                        s.git(["dupe"].iter().chain(words)).from(&dir),
                        &s.dir().join("trace"),
                    );
                    let took = started.elapsed();
                    assert_eq!(output.end, End::Code(0), "git dupe {words:?}: {output:?}");
                    let own = runs.own();
                    let runs = own.commands().into_iter().map(<[u8]>::to_vec).collect();
                    measured[command][at].push(Measured { runs, took });
                }
                // `switch` rewrote the private files to the other branch, which lacks this
                // round's line, and switching back brings it again.
                assert!(
                    !first_private_file_holds(&dir, &line),
                    "after switch {OTHER}"
                );
                s.git(["dupe", "switch", "main"]).from(&dir).succeeds();
                assert!(first_private_file_holds(&dir, &line), "after switch main");
            }
        }
        let after = public_status_timings(s, &dir);
        let listed = s.git(["status", "--porcelain", "-z"]).from(&dir).succeeds();

        for (words, measured) in COMMANDS.into_iter().zip(&measured) {
            let counts = measured.iter().map(|rounds| {
                let counts: Vec<String> = rounds.iter().map(|r| r.runs.len().to_string()).collect();
                counts.join(",")
            });
            let counts: Vec<String> = counts.collect();
            let took = |size: usize| {
                let took = measured[size].iter().map(|measured| measured.took);
                let (least, greatest) = (took.clone().min(), took.max());
                (
                    seconds(least.expect("a round")),
                    seconds(greatest.expect("a round")),
                )
            };
            let ((least_small, greatest_small), (least_large, greatest_large)) = (took(0), took(1));
            report(&format!(
                "Git {version}, {PUBLIC_FILES} public files: `git dupe {}` ran Git {} times at \
                 {} and {} at {} private files, the sequence written being {}; least of \
                 {ROUNDS} rounds {least_small} and {least_large} (greatest {greatest_small} and \
                 {greatest_large})",
                words.join(" "),
                counts[0],
                SIZES[0],
                counts[1],
                SIZES[1],
                sequence(words[0]).join(" "),
            ));
        }
        let greatest_before = before.iter().max().expect("timings before");
        let least_after = after.iter().min().expect("timings after");
        report(&format!(
            "Git {version}, {PUBLIC_FILES} public files: public `git status` {PUBLIC_TIMINGS} \
             times before `git dupe init`, least {} and greatest {}; {PUBLIC_TIMINGS} times after \
             the last round, least {} and greatest {}",
            seconds(*before.iter().min().expect("timings before")),
            seconds(*greatest_before),
            seconds(*least_after),
            seconds(*after.iter().max().expect("timings after")),
        ));

        for (words, measured) in COMMANDS.into_iter().zip(&measured) {
            let written = sequence(words[0]);
            for (size, rounds) in SIZES.into_iter().zip(measured) {
                for (round, measured) in rounds.iter().enumerate() {
                    let runs: Vec<String> = measured
                        .runs
                        .iter()
                        .map(|word| String::from_utf8_lossy(word).into_owned())
                        .collect();
                    assert_eq!(
                        runs, written,
                        "git dupe {words:?} at {size} private files, round {round}"
                    );
                }
                let least = least(rounds);
                assert!(
                    least < BOUND,
                    "git dupe {words:?} at {size} private files took {least:?} at least"
                );
            }
        }
        assert!(
            least_after <= greatest_before,
            "public git status: before {before:?}, after {after:?}"
        );
        // The public files are as committed and every private one is hidden, so public
        // status lists nothing at all, and so no private path.
        assert!(listed.stdout.is_empty(), "{listed:?}");
    });
}

/// Makes `dir` a repository on `main` of `PUBLIC_FILES` empty files, committed, with the
/// identity private commits take from it through `init` (G1).
fn generate(s: &Scenario, dir: &Path) {
    fs::create_dir(dir).unwrap_or_else(|cause| panic!("{}: {cause}", dir.display()));
    s.git(["init", "-q", "-b", "main"]).from(dir).succeeds();
    for (key, value) in [
        ("user.name", "Scale Scenario"),
        ("user.email", "scale@example.invalid"),
    ] {
        s.git(["config", key, value]).from(dir).succeeds();
    }
    // Older than the index Git is about to write, as a project's files are: a file written
    // in the same second as the index is racily clean, and every status reads it again.
    let older = SystemTime::now() - Duration::from_secs(60);
    for directory in 0..DIRECTORIES {
        let directory = dir.join(format!("d{directory:02}"));
        fs::create_dir(&directory)
            .unwrap_or_else(|cause| panic!("{}: {cause}", directory.display()));
        for file in 0..FILES_PER_DIRECTORY {
            let file = directory.join(format!("f{file:04}"));
            File::create(&file)
                .and_then(|created| created.set_modified(older))
                .unwrap_or_else(|cause| panic!("{}: {cause}", file.display()));
        }
    }
    s.git(["add", "."]).from(dir).succeeds();
    s.git(["commit", "-q", "-m", "public files"])
        .from(dir)
        .succeeds();
    let tracked = s.git(["ls-files", "-z"]).from(dir).succeeds();
    let tracked = tracked.stdout.iter().filter(|&&byte| byte == 0).count();
    assert_eq!(tracked, PUBLIC_FILES, "publicly tracked files");
}

/// The private file numbered `number`, in one of the hidden directories.
fn private_file(number: usize) -> String {
    format!("{}/p{number:04}", HIDDEN[number % HIDDEN.len()])
}

fn write_private_files(dir: &Path, numbers: std::ops::Range<usize>) {
    for number in numbers {
        let file = dir.join(private_file(number));
        fs::create_dir_all(file.parent().expect("a hidden directory"))
            .and_then(|()| fs::write(&file, format!("{}\n", private_file(number))))
            .unwrap_or_else(|cause| panic!("{}: {cause}", file.display()));
    }
}

/// Appends a line to each of the first `files` private files.
fn change_private_files(dir: &Path, files: usize, line: &str) {
    for number in 0..files {
        let file = dir.join(private_file(number));
        OpenOptions::new()
            .append(true)
            .open(&file)
            .and_then(|mut opened| writeln!(opened, "{line}"))
            .unwrap_or_else(|cause| panic!("{}: {cause}", file.display()));
    }
}

/// Untimed `git dupe status --porcelain -z`: it must list each of the first `files`
/// private files as changed in the working tree, and nothing else.
fn status_lists_the_changed_private_files_alone(s: &Scenario, dir: &Path, files: usize) {
    let status = s
        .git(["dupe", "status", "--porcelain", "-z"])
        .from(dir)
        .succeeds();
    let listed: Vec<&[u8]> = status
        .stdout
        .split(|&byte| byte == 0)
        .filter(|entry| !entry.is_empty())
        .collect();
    let mut changed: Vec<Vec<u8>> = (0..files)
        .map(|number| format!(" M {}", private_file(number)).into_bytes())
        .collect();
    changed.sort_unstable();
    let stray: Vec<String> = listed
        .iter()
        .filter(|entry| {
            changed
                .binary_search_by(|path| path.as_slice().cmp(entry))
                .is_err()
        })
        .take(5)
        .map(|entry| entry.escape_ascii().to_string())
        .collect();
    assert!(
        listed.len() == files && stray.is_empty(),
        "git dupe status listed {} entries for {files} changed private files; among the \
         others: {stray:?}",
        listed.len()
    );
}

/// Whether the first private file holds `line` as one of its lines.
fn first_private_file_holds(dir: &Path, line: &str) -> bool {
    let file = dir.join(private_file(0));
    let bytes = fs::read(&file).unwrap_or_else(|cause| panic!("{}: {cause}", file.display()));
    bytes
        .split(|&byte| byte == b'\n')
        .any(|held| held == line.as_bytes())
}

/// Public `git status` timed `PUBLIC_TIMINGS` times, after one untimed run.
fn public_status_timings(s: &Scenario, dir: &Path) -> Vec<Duration> {
    s.git(["status"]).from(dir).succeeds();
    (0..PUBLIC_TIMINGS)
        .map(|_| {
            let started = Instant::now();
            s.git(["status"]).from(dir).succeeds();
            started.elapsed()
        })
        .collect()
}

fn seconds(duration: Duration) -> String {
    format!("{:.3} s", duration.as_secs_f64())
}

fn least(rounds: &[Measured]) -> Duration {
    rounds
        .iter()
        .map(|measured| measured.took)
        .min()
        .expect("a round")
}
